// Mobius SSH is a deliberately small SSH/SFTP client for Mobius Device Lab.
// It accepts only the argument subset generated by the desktop application.
package main

import (
	"errors"
	"fmt"
	"io"
	"net"
	"os"
	"os/signal"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"time"

	"github.com/pkg/sftp"
	"golang.org/x/crypto/ssh"
	"golang.org/x/crypto/ssh/knownhosts"
)

const (
	version            = "0.2.0"
	defaultPort        = 22
	maxPrivateKeyBytes = 1024 * 1024
	maxPasswordBytes   = 1024
	brokerTokenLength  = 64
	hostKeyLockTimeout = 2 * time.Second
	staleHostKeyLock   = 30 * time.Second
	brokerMarkerEnv    = "MOBIUS_SSH_ASKPASS"
	brokerPortEnv      = "MOBIUS_SSH_ASKPASS_PORT"
	legacyEndpointEnv  = "MOBIUS_SSH_ASKPASS_ENDPOINT"
	brokerTokenEnv     = "MOBIUS_SSH_ASKPASS_TOKEN"
)

type clientOptions struct {
	port             uint16
	knownHostsPath   string
	hostKeyAlias     string
	identityPath     string
	passwordEnabled  bool
	connectTimeout   time.Duration
	serverAlive      time.Duration
	serverAliveCount int
	noCommand        bool
	localForward     *forwardSpec
	remoteForward    *forwardSpec
	username         string
	host             string
	command          string
}

type forwardSpec struct {
	bindHost   string
	bindPort   uint16
	targetHost string
	targetPort uint16
}

func main() {
	code, err := run(filepath.Base(os.Args[0]), os.Args[1:])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
	}
	os.Exit(code)
}

func run(program string, args []string) (int, error) {
	if len(args) == 1 && (args[0] == "-V" || args[0] == "--version") {
		fmt.Printf("Mobius SSH/SFTP Client %s (x/crypto/ssh)\n", version)
		return 0, nil
	}
	if strings.EqualFold(strings.TrimSuffix(program, filepath.Ext(program)), "scp") {
		return runSCP(args)
	}
	return runSSH(args)
}

func runSSH(args []string) (int, error) {
	opts, err := parseSSHArgs(args)
	if err != nil {
		return 255, err
	}
	client, err := connect(opts)
	if err != nil {
		return 255, err
	}
	defer client.Close()

	if opts.localForward != nil || opts.remoteForward != nil {
		return runTunnels(client, opts)
	}
	if opts.noCommand || opts.command == "" {
		return 255, errors.New("mobius-ssh: a command or managed forwarding request is required")
	}

	session, err := client.NewSession()
	if err != nil {
		return 255, fmt.Errorf("mobius-ssh: create session: %w", err)
	}
	defer session.Close()
	session.Stdin = os.Stdin
	session.Stdout = os.Stdout
	session.Stderr = os.Stderr
	if err := session.Run(opts.command); err != nil {
		var exitError *ssh.ExitError
		if errors.As(err, &exitError) {
			return exitError.ExitStatus(), nil
		}
		return 255, fmt.Errorf("mobius-ssh: remote command: %w", err)
	}
	return 0, nil
}

func runSCP(args []string) (int, error) {
	opts, source, destination, err := parseSCPArgs(args)
	if err != nil {
		return 255, err
	}
	remoteSource, sourceRemote := parseRemoteSpec(source)
	remoteDestination, destinationRemote := parseRemoteSpec(destination)
	if sourceRemote == destinationRemote {
		return 255, errors.New("mobius-scp: exactly one path must be remote")
	}
	remote := remoteSource
	if destinationRemote {
		remote = remoteDestination
	}
	opts.username = remote.username
	opts.host = remote.host

	client, err := connect(opts)
	if err != nil {
		return 255, err
	}
	defer client.Close()
	sftpClient, err := sftp.NewClient(client)
	if err != nil {
		return 255, fmt.Errorf("mobius-scp: start SFTP subsystem: %w", err)
	}
	defer sftpClient.Close()

	if sourceRemote {
		err = downloadFile(sftpClient, remoteSource.path, destination)
	} else {
		err = uploadFile(sftpClient, source, remoteDestination.path)
	}
	if err != nil {
		return 1, err
	}
	return 0, nil
}

func parseSSHArgs(args []string) (*clientOptions, error) {
	opts := defaultOptions()
	position := 0
	for position < len(args) {
		arg := args[position]
		if arg == "--" {
			position++
			break
		}
		if !strings.HasPrefix(arg, "-") || arg == "-" {
			break
		}
		switch arg {
		case "-T":
			position++
		case "-N":
			opts.noCommand = true
			position++
		case "-F", "-p", "-o", "-i", "-L", "-R":
			if position+1 >= len(args) {
				return nil, fmt.Errorf("mobius-ssh: %s requires a value", arg)
			}
			value := args[position+1]
			position += 2
			if err := applyOption(opts, arg, value); err != nil {
				return nil, err
			}
		default:
			return nil, fmt.Errorf("mobius-ssh: unsupported argument %q", arg)
		}
	}
	if position >= len(args) {
		return nil, errors.New("mobius-ssh: missing user@host target")
	}
	if err := parseTarget(opts, args[position]); err != nil {
		return nil, err
	}
	position++
	if position < len(args) {
		opts.command = strings.Join(args[position:], " ")
	}
	if opts.knownHostsPath == "" {
		return nil, errors.New("mobius-ssh: UserKnownHostsFile is required")
	}
	if opts.noCommand && opts.localForward == nil && opts.remoteForward == nil {
		return nil, errors.New("mobius-ssh: -N requires -L or -R")
	}
	return opts, nil
}

func parseSCPArgs(args []string) (*clientOptions, string, string, error) {
	opts := defaultOptions()
	position := 0
	for position < len(args) {
		arg := args[position]
		if arg == "--" {
			position++
			break
		}
		if !strings.HasPrefix(arg, "-") || arg == "-" {
			break
		}
		switch arg {
		case "-B", "-s":
			// -s forces SFTP mode in OpenSSH 8.7 through 8.9 and remains
			// accepted by newer releases. This helper is always SFTP-only, so
			// accepting it preserves the same no-remote-shell path semantics.
			position++
		case "-F", "-P", "-o", "-i":
			if position+1 >= len(args) {
				return nil, "", "", fmt.Errorf("mobius-scp: %s requires a value", arg)
			}
			value := args[position+1]
			position += 2
			mapped := arg
			if arg == "-P" {
				mapped = "-p"
			}
			if err := applyOption(opts, mapped, value); err != nil {
				return nil, "", "", err
			}
		default:
			return nil, "", "", fmt.Errorf("mobius-scp: unsupported argument %q", arg)
		}
	}
	if len(args)-position != 2 {
		return nil, "", "", errors.New("mobius-scp: exactly one source and destination are required")
	}
	if opts.knownHostsPath == "" {
		return nil, "", "", errors.New("mobius-scp: UserKnownHostsFile is required")
	}
	return opts, args[position], args[position+1], nil
}

func defaultOptions() *clientOptions {
	return &clientOptions{
		port:             defaultPort,
		connectTimeout:   8 * time.Second,
		serverAlive:      15 * time.Second,
		serverAliveCount: 2,
	}
}

func applyOption(opts *clientOptions, flag, value string) error {
	switch flag {
	case "-F":
		if value != "none" {
			return errors.New("mobius-ssh: only the isolated configuration -F none is supported")
		}
	case "-p":
		port, err := parsePort(value)
		if err != nil {
			return fmt.Errorf("mobius-ssh: invalid port: %w", err)
		}
		opts.port = port
	case "-i":
		if value == "" {
			return errors.New("mobius-ssh: empty private-key path")
		}
		opts.identityPath = value
	case "-L", "-R":
		forward, err := parseForward(value)
		if err != nil {
			return fmt.Errorf("mobius-ssh: invalid %s forward: %w", flag, err)
		}
		if flag == "-L" {
			if opts.localForward != nil || opts.remoteForward != nil {
				return errors.New("mobius-ssh: exactly one managed forward is supported")
			}
			opts.localForward = &forward
		} else {
			if opts.localForward != nil || opts.remoteForward != nil {
				return errors.New("mobius-ssh: exactly one managed forward is supported")
			}
			opts.remoteForward = &forward
		}
	case "-o":
		return applyNamedOption(opts, value)
	default:
		return fmt.Errorf("mobius-ssh: unsupported option %q", flag)
	}
	return nil
}

func applyNamedOption(opts *clientOptions, value string) error {
	parts := strings.SplitN(value, "=", 2)
	if len(parts) != 2 || parts[0] == "" {
		return fmt.Errorf("mobius-ssh: invalid -o value %q", value)
	}
	name, setting := strings.ToLower(parts[0]), parts[1]
	switch name {
	case "stricthostkeychecking":
		if setting != "accept-new" {
			return errors.New("mobius-ssh: StrictHostKeyChecking must be accept-new")
		}
	case "userknownhostsfile":
		if setting == "" {
			return errors.New("mobius-ssh: UserKnownHostsFile cannot be empty")
		}
		opts.knownHostsPath = setting
	case "connecttimeout":
		seconds, err := parsePositiveInt(setting, 1, 60)
		if err != nil {
			return fmt.Errorf("mobius-ssh: invalid ConnectTimeout: %w", err)
		}
		opts.connectTimeout = time.Duration(seconds) * time.Second
	case "serveraliveinterval":
		seconds, err := parsePositiveInt(setting, 1, 300)
		if err != nil {
			return fmt.Errorf("mobius-ssh: invalid ServerAliveInterval: %w", err)
		}
		opts.serverAlive = time.Duration(seconds) * time.Second
	case "serveralivecountmax":
		count, err := parsePositiveInt(setting, 1, 10)
		if err != nil {
			return fmt.Errorf("mobius-ssh: invalid ServerAliveCountMax: %w", err)
		}
		opts.serverAliveCount = count
	case "hostkeyalias":
		if !validHostKeyAlias(setting) {
			return errors.New("mobius-ssh: invalid HostKeyAlias")
		}
		opts.hostKeyAlias = setting
	case "batchmode", "identitiesonly", "pubkeyauthentication", "passwordauthentication", "kbdinteractiveauthentication", "preferredauthentications", "numberofpasswordprompts", "loglevel", "exitonforwardfailure", "gatewayports":
		if err := validateFixedNamedOption(name, setting); err != nil {
			return err
		}
		if name == "passwordauthentication" {
			opts.passwordEnabled = setting == "yes"
		}
	default:
		return fmt.Errorf("mobius-ssh: unsupported -o option %q", parts[0])
	}
	return nil
}

func validHostKeyAlias(value string) bool {
	if value == "" || len(value) > 255 {
		return false
	}
	for _, char := range value {
		if !(char >= 'a' && char <= 'z' || char >= 'A' && char <= 'Z' || char >= '0' && char <= '9' || strings.ContainsRune("_.-", char)) {
			return false
		}
	}
	return true
}

func validateFixedNamedOption(name, value string) error {
	allowed := map[string]map[string]bool{
		"batchmode":                    {"yes": true, "no": true},
		"identitiesonly":               {"yes": true},
		"pubkeyauthentication":         {"no": true},
		"passwordauthentication":       {"no": true, "yes": true},
		"kbdinteractiveauthentication": {"no": true},
		"preferredauthentications":     {"publickey": true, "password": true},
		"numberofpasswordprompts":      {"1": true},
		"loglevel":                     {"ERROR": true},
		"exitonforwardfailure":         {"yes": true},
		"gatewayports":                 {"no": true},
	}
	if !allowed[name][value] {
		return fmt.Errorf("mobius-ssh: unsupported %s value %q", name, value)
	}
	return nil
}

func parseTarget(opts *clientOptions, value string) error {
	separator := strings.LastIndex(value, "@")
	if separator <= 0 || separator == len(value)-1 {
		return errors.New("mobius-ssh: target must be user@host")
	}
	opts.username = value[:separator]
	opts.host = strings.Trim(value[separator+1:], "[]")
	return validateEndpoint(opts.username, opts.host)
}

type remotePath struct {
	username string
	host     string
	path     string
}

func parseRemoteSpec(value string) (remotePath, bool) {
	at := strings.Index(value, "@")
	if at <= 0 || at == len(value)-1 {
		return remotePath{}, false
	}
	remainder := value[at+1:]
	colon := strings.Index(remainder, ":")
	if strings.HasPrefix(remainder, "[") {
		closing := strings.Index(remainder, "]:")
		if closing < 0 {
			return remotePath{}, false
		}
		colon = closing + 1
	}
	if colon <= 0 || colon == len(remainder)-1 {
		return remotePath{}, false
	}
	remote := remotePath{
		username: value[:at],
		host:     strings.Trim(remainder[:colon], "[]"),
		path:     remainder[colon+1:],
	}
	if validateEndpoint(remote.username, remote.host) != nil || strings.ContainsAny(remote.path, "\r\n\x00") {
		return remotePath{}, false
	}
	return remote, true
}

func validateEndpoint(username, host string) error {
	if username == "" || len(username) > 64 || strings.HasPrefix(username, "-") {
		return errors.New("mobius-ssh: invalid username")
	}
	for _, char := range username {
		if !(char >= 'a' && char <= 'z' || char >= 'A' && char <= 'Z' || char >= '0' && char <= '9' || strings.ContainsRune("_.-", char)) {
			return errors.New("mobius-ssh: invalid username")
		}
	}
	ip := net.ParseIP(host)
	if ip == nil || !isLocalAddress(ip) {
		return errors.New("mobius-ssh: host must be a private, loopback, or link-local IP address")
	}
	return nil
}

func isLocalAddress(ip net.IP) bool {
	return ip.IsLoopback() || ip.IsLinkLocalUnicast() || ip.IsPrivate()
}

func parseForward(value string) (forwardSpec, error) {
	parts := strings.Split(value, ":")
	if len(parts) != 4 {
		return forwardSpec{}, errors.New("expected bind-host:bind-port:target-host:target-port")
	}
	bindPort, err := parsePort(parts[1])
	if err != nil {
		return forwardSpec{}, err
	}
	targetPort, err := parsePort(parts[3])
	if err != nil {
		return forwardSpec{}, err
	}
	if parts[0] != "127.0.0.1" || parts[2] != "127.0.0.1" {
		return forwardSpec{}, errors.New("both forward endpoints must be 127.0.0.1")
	}
	return forwardSpec{parts[0], bindPort, parts[2], targetPort}, nil
}

func parsePort(value string) (uint16, error) {
	port, err := strconv.ParseUint(value, 10, 16)
	if err != nil || port == 0 {
		return 0, errors.New("port must be between 1 and 65535")
	}
	return uint16(port), nil
}

func parsePositiveInt(value string, minimum, maximum int) (int, error) {
	number, err := strconv.Atoi(value)
	if err != nil || number < minimum || number > maximum {
		return 0, fmt.Errorf("value must be between %d and %d", minimum, maximum)
	}
	return number, nil
}

func connect(opts *clientOptions) (*ssh.Client, error) {
	auth, cleanup, err := authentication(opts)
	if err != nil {
		return nil, err
	}
	defer cleanup()
	hostKeyCallback, err := acceptNewHostKey(opts.knownHostsPath, opts.hostKeyAlias)
	if err != nil {
		return nil, err
	}
	config := &ssh.ClientConfig{
		User:              opts.username,
		Auth:              []ssh.AuthMethod{auth},
		HostKeyCallback:   hostKeyCallback,
		HostKeyAlgorithms: hostKeyAlgorithms(),
		Timeout:           opts.connectTimeout,
		Config: ssh.Config{
			// Older jailbreak OpenSSH builds may only offer group14-sha1.
			// Keep that bounded compatibility KEX, but never enable group1,
			// DSA, CBC ciphers, or the other insecure algorithm set.
			KeyExchanges: keyExchanges(),
			Ciphers:      ssh.SupportedAlgorithms().Ciphers,
			MACs:         ssh.SupportedAlgorithms().MACs,
		},
	}
	address := net.JoinHostPort(opts.host, strconv.Itoa(int(opts.port)))
	dialer := net.Dialer{Timeout: opts.connectTimeout}
	connection, err := dialer.Dial("tcp", address)
	if err != nil {
		return nil, fmt.Errorf("mobius-ssh: connect to %s: %w", address, err)
	}
	deadline := time.Now().Add(opts.connectTimeout)
	_ = connection.SetDeadline(deadline)
	clientConnection, channels, requests, err := ssh.NewClientConn(connection, address, config)
	config.Auth = nil
	_ = connection.SetDeadline(time.Time{})
	if err != nil {
		connection.Close()
		return nil, fmt.Errorf("mobius-ssh: handshake: %w", err)
	}
	return ssh.NewClient(clientConnection, channels, requests), nil
}

func hostKeyAlgorithms() []string {
	return append(ssh.SupportedAlgorithms().HostKeys, ssh.KeyAlgoRSA)
}

func keyExchanges() []string {
	return append(
		ssh.SupportedAlgorithms().KeyExchanges,
		ssh.InsecureKeyExchangeDH14SHA1,
	)
}

func authentication(opts *clientOptions) (ssh.AuthMethod, func(), error) {
	if opts.identityPath != "" {
		contents, err := os.ReadFile(opts.identityPath)
		if err != nil {
			return nil, func() {}, fmt.Errorf("mobius-ssh: read private key: %w", err)
		}
		if len(contents) == 0 || len(contents) > maxPrivateKeyBytes {
			overwrite(contents)
			return nil, func() {}, errors.New("mobius-ssh: private key must be between 1 byte and 1 MiB")
		}
		signer, err := ssh.ParsePrivateKey(contents)
		overwrite(contents)
		if err != nil {
			return nil, func() {}, fmt.Errorf("mobius-ssh: parse unencrypted private key: %w", err)
		}
		return ssh.PublicKeys(signer), func() {}, nil
	}
	if !opts.passwordEnabled {
		return nil, func() {}, errors.New("mobius-ssh: no supported authentication method was selected")
	}
	password, err := readBrokerPassword()
	if err != nil {
		return nil, func() {}, err
	}
	method := ssh.Password(string(password))
	return method, func() { overwrite(password) }, nil
}

func readBrokerPassword() ([]byte, error) {
	if os.Getenv(brokerMarkerEnv) != "1" {
		return nil, errors.New("mobius-ssh: one-time password broker is unavailable")
	}
	portText := os.Getenv(brokerPortEnv)
	token := os.Getenv(brokerTokenEnv)
	_ = os.Unsetenv(brokerMarkerEnv)
	_ = os.Unsetenv(brokerPortEnv)
	_ = os.Unsetenv(legacyEndpointEnv)
	_ = os.Unsetenv(brokerTokenEnv)
	port, err := parsePort(portText)
	if err != nil {
		return nil, errors.New("mobius-ssh: invalid password broker port")
	}
	if len(token) != brokerTokenLength {
		return nil, errors.New("mobius-ssh: invalid password broker capability")
	}
	for _, char := range token {
		if !(char >= '0' && char <= '9' || char >= 'a' && char <= 'f') {
			return nil, errors.New("mobius-ssh: invalid password broker capability")
		}
	}
	// The broker address is deliberately not configurable. Only its ephemeral
	// port crosses the process boundary, so malformed or inherited state cannot
	// redirect a credential request away from IPv4 loopback.
	address := net.JoinHostPort("127.0.0.1", strconv.Itoa(int(port)))
	connection, err := net.DialTimeout("tcp", address, 2*time.Second)
	if err != nil {
		return nil, fmt.Errorf("mobius-ssh: connect password broker: %w", err)
	}
	defer connection.Close()
	_ = connection.SetDeadline(time.Now().Add(2 * time.Second))
	if _, err := io.WriteString(connection, token+"\n"); err != nil {
		return nil, fmt.Errorf("mobius-ssh: authenticate password broker: %w", err)
	}
	if tcp, ok := connection.(*net.TCPConn); ok {
		_ = tcp.CloseWrite()
	}
	limited := io.LimitReader(connection, maxPasswordBytes+1)
	password, err := io.ReadAll(limited)
	if err != nil {
		overwrite(password)
		return nil, fmt.Errorf("mobius-ssh: read password broker: %w", err)
	}
	if len(password) == 0 || len(password) > maxPasswordBytes {
		overwrite(password)
		return nil, errors.New("mobius-ssh: password broker returned an invalid secret")
	}
	return password, nil
}

func acceptNewHostKey(path, alias string) (ssh.HostKeyCallback, error) {
	info, err := os.Lstat(path)
	if err != nil {
		return nil, fmt.Errorf("mobius-ssh: inspect known-hosts file: %w", err)
	}
	if !info.Mode().IsRegular() {
		return nil, errors.New("mobius-ssh: known-hosts path must be a regular file")
	}
	callback, err := knownhosts.New(path)
	if err != nil {
		return nil, fmt.Errorf("mobius-ssh: read known-hosts file: %w", err)
	}
	return func(hostname string, remote net.Addr, key ssh.PublicKey) error {
		lookup := hostname
		if alias != "" {
			// knownhosts callbacks require host:port input. OpenSSH's
			// HostKeyAlias is intentionally port-independent, so represent it
			// with the default port and persist the normalized bare alias.
			lookup = net.JoinHostPort(alias, strconv.Itoa(defaultPort))
		}
		err := callback(lookup, remote, key)
		if err == nil {
			return nil
		}
		var keyError *knownhosts.KeyError
		if !errors.As(err, &keyError) || len(keyError.Want) != 0 {
			return fmt.Errorf("mobius-ssh: host key verification failed: %w", err)
		}
		return appendUnknownHostKey(path, lookup, remote, key)
	}, nil
}

func appendUnknownHostKey(path, lookup string, remote net.Addr, key ssh.PublicKey) error {
	release, err := acquireHostKeyLock(path + ".lock")
	if err != nil {
		return err
	}
	defer release()

	// Another helper may have pinned this host between the initial lookup and
	// lock acquisition. Reload under the cross-process lock and accept only an
	// exact match; this prevents two simultaneous first connections from
	// pinning two different keys for one device alias.
	callback, err := knownhosts.New(path)
	if err != nil {
		return fmt.Errorf("mobius-ssh: reload known-hosts file: %w", err)
	}
	err = callback(lookup, remote, key)
	if err == nil {
		return nil
	}
	var keyError *knownhosts.KeyError
	if !errors.As(err, &keyError) || len(keyError.Want) != 0 {
		return fmt.Errorf("mobius-ssh: host key verification failed: %w", err)
	}

	lineHost := knownhosts.Normalize(lookup)
	line := knownhosts.Line([]string{lineHost}, key) + "\n"
	file, openErr := os.OpenFile(path, os.O_WRONLY|os.O_APPEND, 0o600)
	if openErr != nil {
		return fmt.Errorf("mobius-ssh: append known host: %w", openErr)
	}
	_, writeErr := io.WriteString(file, line)
	closeErr := file.Close()
	if writeErr != nil {
		return fmt.Errorf("mobius-ssh: append known host: %w", writeErr)
	}
	if closeErr != nil {
		return fmt.Errorf("mobius-ssh: close known-hosts file: %w", closeErr)
	}
	return nil
}

func acquireHostKeyLock(path string) (func(), error) {
	deadline := time.Now().Add(hostKeyLockTimeout)
	for {
		file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
		if err == nil {
			if closeErr := file.Close(); closeErr != nil {
				_ = os.Remove(path)
				return nil, fmt.Errorf("mobius-ssh: create host-key lock: %w", closeErr)
			}
			return func() { _ = os.Remove(path) }, nil
		}
		if !errors.Is(err, os.ErrExist) {
			return nil, fmt.Errorf("mobius-ssh: create host-key lock: %w", err)
		}
		if info, statErr := os.Lstat(path); statErr == nil && time.Since(info.ModTime()) > staleHostKeyLock {
			_ = os.Remove(path)
			continue
		}
		if time.Now().After(deadline) {
			return nil, errors.New("mobius-ssh: timed out waiting for the host-key lock")
		}
		time.Sleep(10 * time.Millisecond)
	}
}

func downloadFile(client *sftp.Client, remotePath, localPath string) error {
	remote, err := client.Open(remotePath)
	if err != nil {
		return fmt.Errorf("mobius-scp: open remote file: %w", err)
	}
	defer remote.Close()
	if info, err := remote.Stat(); err != nil || !info.Mode().IsRegular() {
		return errors.New("mobius-scp: remote source must be a regular file")
	}
	if info, err := os.Stat(localPath); err == nil && info.IsDir() {
		localPath = filepath.Join(localPath, filepath.Base(remotePath))
	}
	if info, err := os.Lstat(localPath); err == nil && info.Mode()&os.ModeSymlink != 0 {
		return errors.New("mobius-scp: refusing to overwrite a local symbolic link")
	}
	local, err := os.OpenFile(localPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o600)
	if err != nil {
		return fmt.Errorf("mobius-scp: create local file: %w", err)
	}
	_, copyErr := io.Copy(local, remote)
	closeErr := local.Close()
	if copyErr != nil {
		return fmt.Errorf("mobius-scp: download file: %w", copyErr)
	}
	if closeErr != nil {
		return fmt.Errorf("mobius-scp: finish local file: %w", closeErr)
	}
	return nil
}

func uploadFile(client *sftp.Client, localPath, remotePath string) error {
	if info, err := os.Lstat(localPath); err == nil && info.Mode()&os.ModeSymlink != 0 {
		return errors.New("mobius-scp: local source cannot be a symbolic link")
	}
	local, err := os.Open(localPath)
	if err != nil {
		return fmt.Errorf("mobius-scp: open local file: %w", err)
	}
	defer local.Close()
	info, err := local.Stat()
	if err != nil || !info.Mode().IsRegular() {
		return errors.New("mobius-scp: local source must be a regular file")
	}
	if info, err := client.Stat(remotePath); err == nil && info.IsDir() {
		remotePath = strings.TrimRight(remotePath, "/") + "/" + filepath.Base(localPath)
	}
	remote, err := client.OpenFile(remotePath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC)
	if err != nil {
		return fmt.Errorf("mobius-scp: create remote file: %w", err)
	}
	_, copyErr := io.Copy(remote, local)
	closeErr := remote.Close()
	if copyErr != nil {
		return fmt.Errorf("mobius-scp: upload file: %w", copyErr)
	}
	if closeErr != nil {
		return fmt.Errorf("mobius-scp: finish remote file: %w", closeErr)
	}
	return nil
}

func runTunnels(client *ssh.Client, opts *clientOptions) (int, error) {
	var listener net.Listener
	var err error
	var dial func() (net.Conn, error)
	if opts.localForward != nil {
		spec := opts.localForward
		listener, err = net.Listen("tcp", net.JoinHostPort(spec.bindHost, strconv.Itoa(int(spec.bindPort))))
		dial = func() (net.Conn, error) {
			return client.Dial("tcp", net.JoinHostPort(spec.targetHost, strconv.Itoa(int(spec.targetPort))))
		}
	} else if opts.remoteForward != nil {
		spec := opts.remoteForward
		listener, err = client.Listen("tcp", net.JoinHostPort(spec.bindHost, strconv.Itoa(int(spec.bindPort))))
		dial = func() (net.Conn, error) {
			return net.DialTimeout("tcp", net.JoinHostPort(spec.targetHost, strconv.Itoa(int(spec.targetPort))), opts.connectTimeout)
		}
	} else {
		return 255, errors.New("mobius-ssh: managed tunnel specification is missing")
	}
	if err != nil {
		return 255, fmt.Errorf("mobius-ssh: establish managed tunnel: %w", err)
	}
	defer listener.Close()

	done := make(chan error, 2)
	go acceptForwardConnections(listener, dial, done)
	go keepAlive(client, opts.serverAlive, opts.serverAliveCount, done)
	go func() { done <- client.Wait() }()
	interrupts := make(chan os.Signal, 1)
	signal.Notify(interrupts, os.Interrupt, syscall.SIGTERM)
	defer signal.Stop(interrupts)
	select {
	case <-interrupts:
		return 0, nil
	case err := <-done:
		if err == nil || errors.Is(err, net.ErrClosed) || errors.Is(err, io.EOF) {
			return 0, nil
		}
		return 255, fmt.Errorf("mobius-ssh: managed tunnel stopped: %w", err)
	}
}

func acceptForwardConnections(listener net.Listener, dial func() (net.Conn, error), done chan<- error) {
	for {
		incoming, err := listener.Accept()
		if err != nil {
			done <- err
			return
		}
		go func() {
			outgoing, err := dial()
			if err != nil {
				incoming.Close()
				return
			}
			proxy(incoming, outgoing)
		}()
	}
}

func proxy(left, right net.Conn) {
	defer left.Close()
	defer right.Close()
	var wait sync.WaitGroup
	wait.Add(2)
	go func() {
		defer wait.Done()
		_, _ = io.Copy(left, right)
		closeWrite(left)
	}()
	go func() {
		defer wait.Done()
		_, _ = io.Copy(right, left)
		closeWrite(right)
	}()
	wait.Wait()
}

func closeWrite(connection net.Conn) {
	if halfCloser, ok := connection.(interface{ CloseWrite() error }); ok {
		_ = halfCloser.CloseWrite()
	}
}

func keepAlive(client *ssh.Client, interval time.Duration, maximumFailures int, done chan<- error) {
	ticker := time.NewTicker(interval)
	defer ticker.Stop()
	failures := 0
	for range ticker.C {
		_, _, err := client.SendRequest("keepalive@openssh.com", true, nil)
		if err == nil {
			failures = 0
			continue
		}
		failures++
		if failures >= maximumFailures {
			done <- err
			return
		}
	}
}

func overwrite(value []byte) {
	for index := range value {
		value[index] = 0
	}
}
